inherit: true

checks:
  php:
    excluded_dependencies:
      - composer/composer

filter:
  paths:
    - src/*

tools:
  external_code_coverage:
    timeout: 600
  php_code_coverage: true
  php_code_sniffer:
    enabled: true
    config:
      standard: PSR2
  php_cpd: true
  php_cs_fixer: true
  php_loc: true
  php_mess_detector: true
  php_pdepend: true
  php_analyzer: true
  sensiolabs_security_checker: true
  php_changetracking: true
