sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.2
      env:
      - DEPS=lowest
    - php: 7.2
      env:
      - DEPS=latest
    - php: 7.3
      env:
        - DEPS=lowest
    - php: 7.3
      env:
        - DEPS=latest
    - php: 7.4
      env:
        - DEPS=lowest
    - php: 7.4
      env:
        - EXECUTE_CS_CHECK=true
        - EXECUTE_TEST_SCRUTINIZER=true
        - EXECUTE_ANALYSE=true
        - DEPS=locked
    - php: 7.4
      env:
        - DEPS=latest
    - php: nightly
      env:
      - DEPS=lowest
    - php: nightly
      env:
      - DEPS=latest

before_install:
  - composer self-update

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - travis_retry composer install $COMPOSER_ARGS

script:
  - if [[ $EXECUTE_TEST_SCRUTINIZER == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover coverage.clover ; fi
  - if [[ $EXECUTE_TEST_SCRUTINIZER != 'true' ]]; then ./vendor/bin/phpunit ; fi
<<<<<<< HEAD
  - if [[ $EXECUTE_TEST_PHPSTAN != 'true' ]]; then ./vendor/bin/phpstan analyse --no-progress -c phpstan.neon -l7 . ; fi
=======
  - if [[ EXECUTE_ANALYSE == 'true' ]]; then ./vendor/bin/phpstan analyse; fi
>>>>>>> Initial support to composer 2.0
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then DISABLE_RISKY_RULES=true ./vendor/bin/php-cs-fixer fix -v --diff --dry-run; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run --allow-risky yes; fi

after_script:
  - if [[ $EXECUTE_TEST_SCRUTINIZER == 'true' ]]; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ $EXECUTE_TEST_SCRUTINIZER == 'true' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover ; fi
