name: "Continuous Integration"

on:
  pull_request: ~
  push:
    branches:
      - "1.x"
      - "master"
  schedule:
    - cron: "42 3 * * 1"

jobs:
  phpunit:
    name: "Tests"
    runs-on: "ubuntu-24.04"

    strategy:
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
        deps:
          - "highest"
        include:
          - php-version: "8.1"
            deps: "lowest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"
          tools: flex

      - name: Remove Psalm during tests
        run: composer remove --dev --no-update vimeo/psalm psalm/plugin-phpunit

      - name: "Install dependencies"
        uses: ramsey/composer-install@v4
        with:
          dependency-versions: ${{ matrix.deps }}
          composer-options: "--prefer-dist"
        env:
          COMPOSER_NO_SECURITY_BLOCKING: "1"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit --coverage-clover=coverage.xml"

      - name: "Upload coverage"
        uses: codecov/codecov-action@v6
        with:
          files: './coverage.xml'
          fail_ci_if_error: true
          token: ${{ vars.CODECOV_TOKEN }}

      - name: "Run PHP-CS-Fixer (E2E test)"
        run: "vendor/bin/php-cs-fixer fix --dry-run --diff"
        if: "${{ matrix.deps != 'lowest' }}"
        env:
          PHP_CS_FIXER_IGNORE_ENV: true
  Psalm:
    name: "Psalm"
    runs-on: "ubuntu-24.04"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.5"

      - name: "Install dependencies"
        uses: ramsey/composer-install@v4

      - name: "Run Psalm"
        run: "vendor/bin/psalm"
  Rector:
    name: "Rector"
    runs-on: "ubuntu-24.04"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.5"

      - name: "Install dependencies"
        uses: ramsey/composer-install@v4

      - name: "Run Rector"
        run: "vendor/bin/rector --ansi --dry-run"
